image: python:3

before_script:
  - pip install tox

stages:
  - lint
  - test

flake8:
  stage: lint
  script:
    - tox -e flake8

isort:
  stage: lint
  script:
    - tox -e isort

# Wagtail 2.7
py37-dj22-wagtail27:
  image: python:3.7
  stage: test
  script:
    - tox -e py37-dj22-wagtail27

py38-dj22-wagtail27:
  image: python:3.7
  stage: test
  script:
    - tox -e py37-dj22-wagtail27


# Wagtail master
py38-dj22-wagtailmaster:
  image: python:3.8
  stage: test
  script:
    - tox -e py37-dj22-wagtail27
