name: Test

on: [push, pull_request]

jobs:
  lint:
    strategy:
      matrix:
        toxenv: [isort, flake8, black]

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python 3
        uses: actions/setup-python@v2
        with:
          python-version: 3

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install tox

      - name: Run tox - ${{ matrix.toxenv }}
        env:
          TOXENV: ${{ matrix.toxenv }}
        run: tox

  test:
    continue-on-error: ${{ matrix.experimental }}
    strategy:
      matrix:
        include:
          - toxenv: "py37-dj3-wagtail215"
            python-version: "3.7"
            experimental: false
          - toxenv: "py38-dj3-wagtail215"
            python-version: "3.8"
            experimental: false
          - toxenv: "py39-dj3-wagtail215"
            python-version: "3.9"
            experimental: false
          - toxenv: "py310-dj3-wagtail215"
            python-version: "3.10"
            experimental: false
          - toxenv: "py39-dj4-wagtail216"
            python-version: "3.9"
            experimental: false
          - toxenv: "py310-dj4-wagtail216"
            python-version: "3.10"
            experimental: false
          - toxenv: "py39-dj4-wagtail3"
            python-version: "3.9"
            experimental: false
          - toxenv: "py310-dj4-wagtail3"
            python-version: "3.10"
            experimental: false
          - toxenv: "py310-dj4-wagtailmain"
            python-version: "3.10"
            experimental: true
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install tox

      - name: Run tox - ${{ matrix.toxenv }}
        env:
          TOXENV: ${{ matrix.toxenv }}
        run: tox

  build:
    continue-on-error: true
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python 3
        uses: actions/setup-python@v2
        with:
          python-version: 3

      - name: Install dependencies
        run: python -m pip install --upgrade setuptools wheel twine

      - name: Build Python packages
        run: python setup.py bdist_wheel sdist

      - name: twine check
        run: twine check dist/*

      - name: Upload Python packages artifact
        uses: actions/upload-artifact@v1
        with:
          name: Python Packages
          path: dist
